#!/bin/bash

# Input format: #.#.#.#.#
LC=$1

# Split the string
IFS='.' read -r b kt t u k <<< "$LC"

# Calculate total Maya days (Kin)
# For 13.0.0.0.0, this is 1,872,000
maya_days=$(( (b * 144000) + (kt * 7200) + (t * 360) + (u * 20) + k ))

# Offset between Maya Epoch (3114-08-11 BC) and Unix Epoch (1970-01-01)
# The Julian Day for 1970-01-01 is 2440588
# The Julian Day for 3114-08-11 BC is 584283
# Difference: 1,856,305 days
offset=1856305

# Calculate days relative to 1970-01-01
days_since_1970=$(( maya_days - offset ))

# Convert to Gregorian date
# We use 'days' relative to 1970-01-01
result_date=$(date -d "1970-01-01 + $days_since_1970 days" +"%Y-%m-%d")

echo "The Gregorian date for Long Count $LC is: $result_date"

